# Generated by Django 5.0 on 2024-03-16 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelimages',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelreservationidimage',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotelreservation'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='room_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hotel.room'),
        ),
        migrations.AddField(
            model_name='roomimages',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.room'),
        ),
    ]
