# Generated by Django 5.0 on 2024-05-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_rename_room_stay_rename_roomimages_stayimages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='reserved',
        ),
    ]
